---
title: "Inference"
format: html
---

Group: Lena Cole, Mark Patzkowsky, Joël Koelewijn, Stephan Spiekman, Charlotte Summers, Emilia Jarochowska, Davey Wright

Goal:

Infer tree and evolutionary rates across mass extinction events associated with niche shifts, taking into account availability of the niche space changing across time.
Specific case studies:

1. Reptiles across the P/T boundary: did the shift from marine to terrestrial occur once or twice (Sauropterygians and Ichthyosaurs or their common ancestor) and when?

2. Crinoids across the end-Ordovician mass extinction: what was the timing of the post-extinction radiation and is its appearance only after the extinction event an artefact of the rock-record bias?

Tools: https://revbayes.github.io/tutorials/sse/fossils

# Lizard tree

Has extant tips 38/1036 and polytomies. We need to collapse the polytomies.

```{r}
lizards_tree <- read.tree(file = "../Group_Niche_SSE/LizardTree.nex", 
                          text = NULL, 
                          tree.names = NULL, 
                          skip = 0,
                          comment.char = "", 
                          keep.multi = FALSE)

lizards_tree <- ape::multi2di(lizards_tree[[2]])
write.tree(lizards_tree, file="../Group_Niche_SSE/lizards_without_polytomies.nex")
```

Secondly, in the tutorial, there is no option to set time-variable sampling rate, but the function `dnCDBDP` has a `nTimeSlices` parameter which we could try. We don't know anything about it though, but we expect it to work similarly to the skyline psi parameter setup.

Rachel indicated that the setup we are interested in is possible in BEAST2 and she has a tutorial, but we stick with RevBayes for now. She also suggested fixing the tree first. Possibly the best approach would be to take the validation script using by Bruno and simulate a setup similar to ours first.