---
title: "Workshop programme"
author: Emilia Jarochowska, Rachel Warnock, Laura Mulvey, Niklas Hohmann, Johannes
  Hidding
output: pdf_document
---

+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| # Monday    |                                                                                                                   | Emilia Jarochowska and Johannes Hidding |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:00       | Lorentz Center welcome and opening                                                                                |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:15       | Lecture *Principles of Stratigraphic Palaeobiology*                                                               | Mark Patzkowsky                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 11:00       | Ice-breaker group coding activity: *Make your own geological record*                                              | Johannes Hidding and Emilia Jarochowska |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 12:00       | Lunch                                                                                                             |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 13:15       | Ice-breaker group coding activity: *Make your own geological record*                                              | Johannes Hidding and Emilia Jarochowska |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:00       | Lecture *Palaeogeography and plate tectonics in evolution*                                                        | Lydian Boschman                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:45       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 15:15       | Diving deep group coding activity: *Extracting information for phylogenies from strata*                           | Emilia Jarochowska and Johannes Hidding |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 16:30       | Wrap-up: collecting feedback, packing, refreshment break                                                          | All organisers                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 17:00       | Welcome reception                                                                                                 |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| # Tuesday   |                                                                                                                   | Laura Mulvey                            |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 9:15        | Lecture *Modelling morphological evolution*                                                                       | April Wright and Sergey Tarasov         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:00       | Group coding practical: *Incorporating morphological data into phylogenetic analysis*                             | Laura Mulvey                            |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:30       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 11:00       | Group coding practical: *Incorporating morphological data into phylogenetic analysis*                             | Laura Mulvey                            |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 12:00       | Lunch break                                                                                                       |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 13:30       | Lecture *Extensions to Common Morphological Models*                                                               | To be determined                        |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:15       | Breakout group activity: *Challenges in morphological modeling*                                                   | Laura Mulvey                            |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 15:00       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 15:30       | Breakout group activity: *Challenges in morphological modeling*                                                   | Laura Mulvey                            |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 16:30       | Wrap-up and plenary discussion, collecting feedback                                                               | All organisers                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| # Wednesday |                                                                                                                   | Niklas Hohmann and Rachel Warnock       |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 9:00        | Lecture *Fossil Evidence in Time Tree Reconstruction*                                                             | Philip Donoghue                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 9:45        | Lecture *Introduction to the Fossilized Birth-Death Model*                                                        | Alexandra Gavryushkina                  |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:30       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 11:00       | Group coding practical: *A simulation-based approach to integrating stratigraphic paleobiology and phylogenetics* | Rachel Warnock and Niklas Hohmann       |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 12:00       | Lunch break                                                                                                       |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 13:30       | Lecture *Extensions to the FBD processes and challenges*                                                          | Rachel Warnock                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:15       | Group coding practical: *A simulation-based approach to integrating stratigraphic paleobiology and phylogenetics* | Rachel Warnock and Niklas Hohmann       |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:45       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 15:15       | Breakout group activity: *The stratigraphic record as a source of information*                                    | Niklas Hohmann and Rachel Warnock       |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 16:30       | Wrap-up and plenary discussion, collecting feedback                                                               | Niklas Hohmann and Rachel Warnock       |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 18:30       | Workshop dinner                                                                                                   |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| # Thursday  |                                                                                                                   | Rachel Warnock and Niklas Hohmann       |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 9:15        | Lecture *Community led phylogenetic software development*                                                         | Ugne Stolz                              |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:00       | Breakout group activity: *Preparing and reporting data for phylogenetic inference*                                | Rachel Warnock                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:30       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 11:00       | Breakout group activity: *Preparing and reporting data for phylogenetic inference*                                | Rachel Warnock                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 12:00       | Lunch break                                                                                                       |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 13:30       | Lecture *Architecture and limitations of common frameworks used in phylogenetic software development*             | Joëlle Barido-Sottani                   |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:15       | Breakout group activity: *Digital infrastructure for tree inference from fossil data*                             | Rachel Warnock                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:45       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 15:15       | Breakout group activity: *Digital infrastructure for tree inference from fossil data*                             | Rachel Warnock                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 16:30       | Wrap-up and plenary discussion, collecting feedback                                                               | Rachel Warnock                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| # Friday    |                                                                                                                   | All organisers                          |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 9:15        | Breakout group coding and writing activity                                                                        |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:15       | Coffee break                                                                                                      |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 10:45       | Breakout group coding and writing activity                                                                        |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 11:30       | *Plenary summary of the analyses: challenges and results thus far*                                                |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 12:00       | Lunch break                                                                                                       |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 13:30       | Breakout group coding and writing activity                                                                        |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
| 14:30       | Plenary summary and discussion                                                                                    |                                         |
+-------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------+
