---
title: "Reproducibility"
format: html
editor: visual
---

### Task 1 - Reproducibility

*Breakout group activity*\
*Rachel Warnock, Laura Mulvey, Niklas Hohmann, Bethany Allen*

For lots of reasons, it can be difficult to reproduce published phylogenetic analyses or to work out exactly what was done by previous authors. Our aim is to quantify reproducibility among papers that use the FBD model and based on these findings, to make recommendations for future publications. The idea is to increase both the reproducibility and the overall understanding of these models across users. A good understanding of the methodology is usually required to adequately evaluate a study’s findings. We emphasise, the problem of reproducibility is not unique to studies using the FBD model or fossil data (this just happens to be the focus of our workshop), and is a general issue in paleobiology and phylogenetics - therefore some of the issues and recommendations should be broadly applicable.

Your next task is to form small groups and to extract key details from published articles that use the FBD model (2-3 papers, depending on the available time). After the workshop we hope to collect information from all relevant publications (i.e., all studies that have previously used the FBD model). Through this activity we hope to gain your collective insights into how we might refine and scale this process of data collection.

Each group will be assigned a random number and each random number is associated with three papers that you can access here: \<insert link\>.

### Quantifying the reproducibility of studies that use the FBD model

We are interested in extracting information from published articles that relate to reproducibility and overall comprehension of a given analysis. This includes information about the data (phylogenetic characters and age information), model and prior parameter choices, as well as data and code accessibility.

Use the following template to record your results: [Reproducibility_task](Reproducibility_task.docx)

Details of each variable are described below.

Keep track of the following: How long does it take to extract information from each publication? From your perspective, are we collecting all relevant information? Did you encounter any specific challenges? Any suggestions for streamlining this process?

**At the end of the activity please leave 5-10 minutes to write down your thoughts.**

Data collection protocol (adapted from Mulvey et al. 2025)

From Mulvey et al. [FBD survey criteria](https://docs.google.com/document/d/1nHFa01aLEOO7vjFuOUjHN0Ge4XVbadBH_-YD1JvdEi8/edit?tab=t.0)

Notes before you get started

- The spreadsheet is divided into 3 parts: “From the publication”, “Data and code accessibility”, and “From the code”. It is often easier to extract information about the analytical setup from supplementary code than the written text, but since we’re trying to quantify reproducibility we’d like you to answer the questions for each section separately.\
- If you can not obtain any information from the written parts of the paper, you can write ***not found*** in the spreadsheet (do not try to guess).\
- If a particular question is taking an especially long time to answer, just move onto the next one.\
- If a study runs more than one analysis just add it as a new line in the spreadsheet. Most columns will likely be the same but some number might be different, e.g., taxa or characters.\
- Note the survey is not about criticising specific individuals authors or papers, the focus is on collecting information about community wide practices.
