---
title: "Pre-Worshop Meeting"
format: revealjs
---

# Bridging Stratigraphic Palaeobiology and Phylogenetics

28 September - 2 October 2026, Leiden

# Agenda

[needs filling]

# Introductions

# Objectives (1) {.smaller}

1. **draft of a book on phylogenetic reconstruction from simulated data** developed *during* the workshop collaboratively on GitHub.

2. **best-practices recommendations list** for publishing and reviewing phylogenetic analyses and reporting fossil and stratigraphic information.

3. **roadmap for digital infrastructure** needed for landmark use-cases of phylogenetic analysis incorporating fossil data. It will contain a list of priorities from the user perspective.

All contributors will be co-authors, provided that they explicitly review and approve the final draft.

# Objectives (2)

- Strenghtening the communication between users, software developers and model developers

- Translation of researcher needs into digital infrastructure

- Articles on individual research questions developed during the workshop

# Programme of the meeting

[show the programme live in the repo?]

# How we plan to collaborate 

- ad-hoc groups with mixed expertise, centered around a research question

- GitHub secretary takes notes so not everyone needs to edit 

- We use the Quarto publishing system for the online book - your work appears on the website shortly after you have pushed your contribution

- You do not need to be an expert in **all** methods used in the workshop

- We are seeking participants with prior experience with GitHub, R Markdown or Quarto to be the GitHub secretaries

# Logistics

1. Is your travel sorted out?

2. Is your accomodation sorted out?

3. Do you need any other help?
