---
title: "Introduction"
---

Welcome to the online materials for the workshop "Bridging Stratigraphic Paleobiology and Phylogenetics". This page collects all contents (code, text, references, and notes) used during the workshop.

## Installation instructions

Software for phylogenetic inference is spread over multiple software systems. We will use:

-   `git` and GitHub to exchange code and collaborate on its annotation

-   `Julia` for stratigraphic forward simulations

-   `R` for phylogenetic simulations and to build models of stratigraphic paleobiology

-   `revbayes` or `BEAST` for phylogenetic inference

-   `FigTree` and `Tracer` for the visualization of posteriors

-   An IDE (integrated development environment) of your choice (e.g., `VSCode` or `RStudio`) to conveniently interact with this software.

### Git and GitHub - optional

<details>
  <summary>**Why yet another tool, my nerds?**</summary>
  Git is a tool for version control, primarily for code but it works for any text-based files. For us, the most important use is that it will give us a "track-change" mode and we will be able to share everyone's contributions with all participants live. This workshop's purpose is not teaching git, so if you want to keep your mental resources for the science, you will be able to work through the week without using it. However, the goal we want to promote is better reproducibility of phylo/strat projects and better interaction between users and developers. For these goals, using git is essential and we want to support our community memebers in adopting it. So if you haven't had experience with git before and you feel unsure about using it, please reach out to one of the organizers or *git heros* we will mark among the participants and we'll give you a run down. 
</details>
#### Installation

##### Get a GitHub account

Please follow the instructions on GitHub's own [Getting started](https://docs.github.com/en/get-started/onboarding/getting-started-with-your-github-account) page. Choose a free plan. Please note that you will need to [verify your email address](https://docs.github.com/en/account-and-profile/how-tos/email-preferences/verifying-your-email-address) as one of the steps. Secondly, you will be given several options for two-factor authentication (2FA): each of them should work; choose the one that is the most familiar (the lear unfamiliar) to you. You *can* install the GitHub mobile app on your phone, but it is not indispensable.

##### Install a git client

There exist multiple git clients and we won't be experienced in using all of them ourselves. The essentials are:

1. [GitHub Desktop](https://desktop.github.com/) - a graphic user interface available for Windows and Mac, recommended for first-time users
2. [`git`](https://git-scm.com/install/) - a command line interface typically shipped with any Linux, can be installed on MacOS and PowerShell - recommended if you are otherwise accustomed to using the CLI

Configuration instructions will depend on which one you choose, but we focus here on first-time users, so assuming you use GitHub Desktop, you will need to [sign into your GitHub account](https://docs.github.com/en/desktop/overview/getting-started-with-github-desktop) to be able to contribute.

##### Using git to collaborate

If you want to contribute code or text directly from your computer to the workshop's open book, you will need to use operations such as **switching between branches**, **pulling other people's contributions**, **commiting your changes**, and **pushing your changes**. You can collaborate with someone and do this together, or take a look at the [instructions online](https://docs.github.com/en/desktop/overview/getting-started-with-github-desktop#making-changes-in-a-branch) and try on your own. 

::: {.callout-tip}
Remember: as long as you work on a separate branch, you can't break anything - don't hesitate to experiment, this is how you learn.
:::

### Julia

To install Julia, please go to the [Julia Language Downloads](https://julialang.org/install/) page. It will automatically detect your system and provide a link to the correct installation file. It will install `juliaup`, which is a tool for managing Julia installations on your system and takes care of any version issues.

Once you have installed `juliaup`, you can easily install different version of Julia. All Julia code was tested using Julia version 1.13.0, which you can install using

```{bash}
#| eval: false
juliaup add 1.13.0
juliaup default 1.13.0
```


### Installing R, R Studio, and packages

`R` can be directly installed from CRAN (the comprehensive R archive network) [here](https://cran.r-project.org/). Choose the latest version for your operating system and follow the installation instructions. At the time of the workshop, the latest version is R 4.6.1 ("Happy Hop").

You can interact with `R` using the IDE of your choice. Most `R` users are familiar with `RStudio`, which provides a lot of convenient functionality. R Studio can be downloaded from [Posit here](https://docs.posit.co/ide/user/#rstudio-ide-oss-downloads).

Once you have downloaded R, install all required packages by running the following code in R (e.g., in your R Studio console):

```{r}
#| eval: false
install.packages("remotes")
remotes::install_github("fossilsim/morphsim")
remotes::install_github("fossilsim/FossilSim")
remotes::install_github("MindTheGap-ERC/admtools")
remotes::install_github("MindTheGap-ERC/StratPal")
install.packages("TreeSim")
```

## Example workflows

### Variant "User": I don't want to contribute to the book files, I just want to run the code on my computer

Option 1 (no git): You can copy & paste the code from the webpage into new files on your computer; note there is a discrete clipboard icon in the topright corner that copies the entire code block.

Option 2 (minimum git): Clone the repository using the link on its landing page. If you are using GitHub Desktop, https://github.com/MindTheGap-ERC/Lorentz-Workshop should suffice. Open the repository contents in your file system. Most code chunks will run directly when opened in `.qmd` files, e.g. in R Studio or VS Code - this will feel like using a notebook. Alternatively, you can render the `.qmd` files (see above), but this executes all code chunks at once, which is a bit less interactive.

### Variant "Contributor": I want to modify the text or scripts and make my own variants of the analysis. 

1. Give us (organizers) your GitHub name so we can add you to the repository. As an alternative, you could fork it and contribute, but we will not cover this here lest we have further variants and reading the instructions take the remainder of the workshop.

2. Clone the repository onto your computer.

3. Let's take Day 1 as an example. You're looking at the [CarboKitten](https://mindthegap-erc.github.io/Lorentz-Workshop/CarboKitten_tutorial.html) tutorial and you want to run and modify it.

